### ISSUE TITLE
Proposal: Code generation

### ISSUE THREAD

**Issue by sah4ez** [l-vitaly/goenv#1]
Hi! Thanks for you library.
Whats do you think about adding code generation package loading env from `.env` file?
Example. I'm have `.env` in root project:
```
FOO=1
BAR=str
```
I execute `goenv` and output it `pkg/config/config.go`.
```
package config

import (
	"github.com/l-vitaly/goenv"
)

const envErrPattern = "environment variable is not set %s"

// Env vars.
const (
	Foo              = "FOO"
	Bar            = "BAR"
)

// Config config data.
type Config struct {
	Foo              int
	Bar            string
}

// Load load config.
func Load() (*Config, error) {
	cfg := &Config{}
	goenv.IntVar(&cfg.Foo, Foo, "")
	goenv.StringVar(&cfg.Bar, Bar, "")

	goenv.Parse()
	return cfg, nil
}
```
`goenv` can has some options:
**env** - path to .env file (default `.`)
**default** - use values from `.env` as default values
**out** - output path for `config.go` (default `./pkg/config/config.go`)
**no-empty** - add check empty values for string variable (default false)
**err-phare** - custom error ouput for empty values
**verbose** - add verbose ouput process

**Comment by l-vitaly** [comment]
Complete for version v1.3.1
